"""Candice live technical brain.

Live signal direction is generated by asset class:
- REAL assets: AVWAP + Volume Profile + Bill Williams Alligator confirmation.
- OTC assets: PRO Structure Continuation (15M bias -> 1M BOS -> displacement
  -> retest -> hold -> confirmation candle).

The production scheduler, Telegram delivery and DEMO result watcher live in
app.py. The OTC strategy is isolated to assets explicitly identified as OTC;
real assets keep the existing AVWAP + Volume Profile brain.
"""
from __future__ import annotations

import os

import logging
import time
import re
from datetime import datetime, timezone
from math import isfinite

EXPIRIES=(1,2)
MIN_CLOSED_CANDLES=60
ONE_MINUTE=60
FIFTEEN_MINUTES=900
CLOSE_GRACE_SECONDS=1
PROFILE_LOOKBACK=60
PROFILE_BINS=24
VALUE_AREA_FRACTION=0.70
HIGH_VOLUME_MIN_COVERAGE=0.80
ALLOWED_STRATEGY="AVWAP_VOLUME_PROFILE"
OTC_STRATEGY="PRO_OTC_STRUCTURE_CONTINUATION"
LIVE_STRATEGIES=(ALLOWED_STRATEGY,OTC_STRATEGY)

# Bill Williams Alligator confirmation settings, matching the terminal:
# Jaw 13 / shift 8, Teeth 8 / shift 5, Lips 5 / shift 3.
# The Alligator never creates or flips direction; it only confirms the
# authoritative AVWAP + Volume Profile direction.
ALLIGATOR_JAW_PERIOD=13
ALLIGATOR_JAW_SHIFT=8
ALLIGATOR_TEETH_PERIOD=8
ALLIGATOR_TEETH_SHIFT=5
ALLIGATOR_LIPS_PERIOD=5
ALLIGATOR_LIPS_SHIFT=3
ALLIGATOR_MIN_SEPARATION=0.0
# Timing guard: the Alligator confirmation must still refer to the latest
# completed M1 candle at delivery and the jaw/teeth/lips spread must not be
# materially contracting. This is a timing/entry-integrity check, not a
# direction generator.
ALLIGATOR_TIMING_MAX_AGE_SECONDS=90.0
ALLIGATOR_MIN_SPREAD_RATIO=0.98
log=logging.getLogger("candice.brain")
_DIAG_LAST={}

def _diag(pair, reason, **fields):
    now=time.time()
    key=(str(pair),str(reason))
    last=_DIAG_LAST.get(key,0.0)
    if now-last<60.0:
        return
    _DIAG_LAST[key]=now
    log.info("AVWAP_VP_DIAGNOSTIC pair=%s reason=%s fields=%s",pair,reason,fields)



def _f(value, default=0.0):
    try:
        x=float(value)
        return x if isfinite(x) else default
    except (TypeError, ValueError):
        return default


def _ts(value, default=-1.0):
    try:
        x=float(value)
        if x>20_000_000_000:
            x/=1000.0
        return x if isfinite(x) else default
    except (TypeError, ValueError):
        return default


def _extract_volume(raw):
    """Extract broker-supplied real/tick volume without confusing price with volume."""
    if not isinstance(raw,dict):
        return 0.0,"NONE"

    # Explicit real/traded-volume field names first.
    for key in (
        "real_volume","realVolume","trade_volume","tradeVolume",
        "traded_volume","tradedVolume","base_volume","baseVolume",
        "quote_volume","quoteVolume","volume"
    ):
        if key in raw:
            value=_f(raw.get(key),0.0)
            if value>0.0:
                return value,"REAL_VOLUME"

    # Common tick-volume field names. Tick volume is useful, but is not the
    # same thing as traded/notional volume and therefore is not marked real_volume_verified.
    for key in (
        "tick_volume","tickVolume","ticks","tick_count","tickCount",
        "vol","v"
    ):
        if key in raw:
            value=_f(raw.get(key),0.0)
            if value>0.0:
                return value,"TICK_VOLUME"

    # A few broker/API variants nest market statistics under a dict.
    for parent_key in ("data","stats","metrics","meta"):
        nested=raw.get(parent_key)
        if isinstance(nested,dict):
            value,source=_extract_volume(nested)
            if value>0.0:
                return value,source

    return 0.0,"NONE"


def _norm(raw):
    explicit_source=str(raw.get("volume_source") or "").upper()
    if explicit_source=="TICK_ACTIVITY":
        tick_value=0.0
        for key in ("tick_volume","tickVolume","ticks","tick_count","tickCount"):
            tick_value=_f(raw.get(key),0.0)
            if tick_value>0.0:
                volume_source="TICK_ACTIVITY"
                volume=tick_value
                break
        else:
            volume,volume_source=_extract_volume(raw)
    else:
        volume,volume_source=_extract_volume(raw)
    return {
        "time":_ts(raw.get("time",raw.get("t"))),
        "open":_f(raw.get("open",raw.get("o"))),
        "high":_f(raw.get("high",raw.get("h"))),
        "low":_f(raw.get("low",raw.get("l"))),
        "close":_f(raw.get("close",raw.get("c"))),
        "volume":max(volume,0.0),
        "volume_present":bool(volume>0.0),
        "volume_source":volume_source,
        # Explicitly distinguish locally enriched tick activity from broker
        # reported tick volume. Partial sampled minutes are never treated as
        # complete volume observations downstream.
        "tick_activity_proxy":str(raw.get("volume_source") or "").upper()=="TICK_ACTIVITY",
        "tick_activity_observed_seconds":_f(raw.get("tick_activity_observed_seconds"),0.0),
        "tick_activity_complete":bool(raw.get("tick_activity_complete")),
        "tick_activity_source":str(raw.get("tick_activity_source") or "").upper(),
    }


def _closed_1m(candles,now=None):
    now=time.time() if now is None else float(now)
    latest={}
    for raw in candles or []:
        if not isinstance(raw,dict):
            continue
        c=_norm(raw)
        if c["time"]<0:
            continue
        minute=int(c["time"]//ONE_MINUTE)*ONE_MINUTE
        # Never use a currently forming candle.
        if minute+ONE_MINUTE>now-CLOSE_GRACE_SECONDS:
            continue
        c["time"]=minute
        latest[minute]=c
    return [latest[k] for k in sorted(latest)]


def _complete_15m_blocks(cs,now=None):
    now=time.time() if now is None else float(now)
    groups={}
    for c in cs:
        minute=int(c["time"])
        bucket=(minute//FIFTEEN_MINUTES)*FIFTEEN_MINUTES
        if bucket+FIFTEEN_MINUTES>now-CLOSE_GRACE_SECONDS:
            continue
        groups.setdefault(bucket,[]).append(c)

    blocks=[]
    for bucket,bars in sorted(groups.items()):
        bars=sorted(bars,key=lambda x:x["time"])
        expected=[bucket+i*ONE_MINUTE for i in range(15)]
        if [int(x["time"]) for x in bars]!=expected:
            continue
        blocks.append({
            "time":bucket,
            "open":bars[0]["open"],
            "high":max(x["high"] for x in bars),
            "low":min(x["low"] for x in bars),
            "close":bars[-1]["close"],
            "volume":sum(x["volume"] for x in bars),
        })
    return blocks


def _anchored_vwap(cs,anchor_ts):
    sample=[c for c in cs if int(c["time"])>=int(anchor_ts)]
    if not sample:
        return 0.0,0.0
    pv=0.0
    vv=0.0
    for c in sample:
        typical=(c["high"]+c["low"]+c["close"])/3.0
        vol=max(c["volume"],1.0)
        pv+=typical*vol
        vv+=vol
    return (pv/vv if vv else 0.0),vv


def _volume_profile(cs,bins=PROFILE_BINS):
    sample=list(cs[-PROFILE_LOOKBACK:])
    if not sample:
        return None
    low=min(c["low"] for c in sample)
    high=max(c["high"] for c in sample)
    raw_volumes=[]
    volume_sources=[]
    tick_activity_partial_bars=0
    for c in sample:
        source=str(c.get("volume_source") or "NONE").upper()
        value=max(float(c.get("volume",0.0) or 0.0),0.0)
        # A sampled Event-1 minute may have ticks for only part of its 60s.
        # It is useful for diagnostics but must not enter the volume profile
        # as though it were a complete minute of tick activity.
        if source=="TICK_ACTIVITY" and not bool(c.get("tick_activity_complete")):
            value=0.0
            if float(c.get("tick_activity_observed_seconds") or 0.0)>0.0:
                tick_activity_partial_bars+=1
        raw_volumes.append(value)
        volume_sources.append(source)
    volume_bars=sum(1 for v in raw_volumes if v>0.0)
    volume_coverage=volume_bars/max(1,len(sample))
    real_volume_bars=sum(
        1 for v,s in zip(raw_volumes,volume_sources)
        if v>0.0 and s=="REAL_VOLUME"
    )
    tick_volume_bars=sum(
        1 for v,s in zip(raw_volumes,volume_sources)
        if v>0.0 and s=="TICK_VOLUME"
    )
    tick_activity_bars=sum(
        1 for v,s in zip(raw_volumes,volume_sources)
        if v>0.0 and s=="TICK_ACTIVITY"
    )
    real_volume_coverage=real_volume_bars/max(1,len(sample))
    tick_volume_coverage=tick_volume_bars/max(1,len(sample))
    tick_activity_coverage=tick_activity_bars/max(1,len(sample))
    if real_volume_coverage>=0.80:
        volume_mode="REAL_VOLUME"
    elif tick_volume_coverage>=0.80:
        volume_mode="TICK_VOLUME"
    elif tick_activity_coverage>0.0:
        volume_mode="M1_TICK_ACTIVITY_PROXY"
    else:
        volume_mode="M1_EQUAL_ACTIVITY_PROXY"

    if high<=low:
        px=sample[-1]["close"]
        return {
            "poc":px,"vah":px,"val":px,
            "range_high":high,"range_low":low,
            "total_volume":sum(v if v>0 else 1.0 for v in raw_volumes),
            "bins":1,
            "volume_coverage":volume_coverage,
            "volume_mode":volume_mode,
            "volume_bars":volume_bars,
            "real_volume_bars":real_volume_bars,
            "real_volume_coverage":real_volume_coverage,
            "tick_volume_bars":tick_volume_bars,
            "tick_volume_coverage":tick_volume_coverage,
            "tick_activity_bars":tick_activity_bars,
            "tick_activity_coverage":tick_activity_coverage,
            "tick_activity_partial_bars":tick_activity_partial_bars,
        }

    step=(high-low)/float(bins)
    volumes=[0.0]*bins
    for c,v_raw in zip(sample,raw_volumes):
        vol=v_raw if v_raw>0.0 else 1.0
        clo=float(c["low"]); chi=float(c["high"])
        if chi<=clo:
            idx=int((float(c["close"])-low)/step)
            idx=max(0,min(bins-1,idx))
            volumes[idx]+=vol
            continue

        first=max(0,min(bins-1,int((clo-low)/step)))
        last=max(0,min(bins-1,int((chi-low)/step)))
        span=max(chi-clo,1e-12)
        for idx in range(first,last+1):
            row_low=low+idx*step
            row_high=low+(idx+1)*step
            overlap=max(0.0,min(chi,row_high)-max(clo,row_low))
            if overlap>0.0:
                volumes[idx]+=vol*(overlap/span)

    poc_idx=max(range(bins),key=lambda i:(volumes[i],-abs(i-(bins-1)/2.0)))
    target=sum(volumes)*VALUE_AREA_FRACTION
    accumulated=volumes[poc_idx]
    left=right=poc_idx

    while accumulated<target and (left>0 or right<bins-1):
        candidates=[]
        if left>0:
            candidates.append((volumes[left-1],"L"))
        if right<bins-1:
            candidates.append((volumes[right+1],"R"))
        if not candidates:
            break
        next_volume,side=max(candidates,key=lambda item:item[0])
        if accumulated+next_volume>target and accumulated>0:
            break
        if side=="L":
            left-=1
            accumulated+=next_volume
        else:
            right+=1
            accumulated+=next_volume

    return {
        "poc":low+(poc_idx+0.5)*step,
        "vah":min(high,low+(right+1)*step),
        "val":max(low,low+left*step),
        "range_high":high,
        "range_low":low,
        "total_volume":sum(volumes),
        "bins":bins,
        "volume_coverage":volume_coverage,
        "volume_mode":volume_mode,
        "volume_bars":volume_bars,
        "real_volume_bars":real_volume_bars,
        "real_volume_coverage":real_volume_coverage,
        "tick_volume_bars":tick_volume_bars,
        "tick_volume_coverage":tick_volume_coverage,
        "tick_activity_bars":tick_activity_bars,
        "tick_activity_coverage":tick_activity_coverage,
        "tick_activity_partial_bars":tick_activity_partial_bars,
    }


def _profile_migration(cs):
    current=_volume_profile(cs[-PROFILE_LOOKBACK:])
    if not current:
        return None
    previous_sample=cs[-(PROFILE_LOOKBACK*2):-PROFILE_LOOKBACK]
    previous=_volume_profile(previous_sample) if previous_sample else None
    if not previous:
        return {
            "poc_delta":0.0,
            "poc_migration_norm":0.0,
            "previous_poc":None,
            "available":False,
        }
    scale=max(
        abs(float(current["range_high"])-float(current["range_low"])),
        abs(float(previous["range_high"])-float(previous["range_low"])),
        1e-12,
    )
    delta=float(current["poc"])-float(previous["poc"])
    return {
        "poc_delta":delta,
        "poc_migration_norm":delta/scale,
        "previous_poc":float(previous["poc"]),
        "available":True,
    }


def _avwap_slope_features(cs,anchor_ts):
    if len(cs)<3:
        current,_=_anchored_vwap(cs,anchor_ts)
        return {
            "avwap_series":[current],
            "avwap_slope_1":0.0,
            "avwap_slope_2":0.0,
            "avwap_slope_3":0.0,
            "slope_persistence":0,
        }

    values=[]
    for cut in (3,2,1,0):
        subset=cs[:-cut] if cut else cs
        av,_=_anchored_vwap(subset,anchor_ts)
        values.append(float(av))
    s1=values[-1]-values[-2]
    s2=values[-2]-values[-3]
    s3=values[-3]-values[-4]
    pos=sum(1 for s in (s1,s2,s3) if s>0)
    neg=sum(1 for s in (s1,s2,s3) if s<0)
    return {
        "avwap_series":values,
        "avwap_slope_1":s1,
        "avwap_slope_2":s2,
        "avwap_slope_3":s3,
        "slope_persistence":pos if pos>=neg else -neg,
    }


def _slope(cs,anchor_ts):
    if len(cs)<2:
        return 0.0
    current,_=_anchored_vwap(cs,anchor_ts)
    previous,_=_anchored_vwap(cs[:-1],anchor_ts)
    return current-previous


def _m1_sequence_signature(cs,length=6):
    """Compact closed-M1 price geometry signature; no new indicator."""
    sample=list(cs[-max(3,int(length)):])
    parts=[]
    for c in sample:
        try:
            o=float(c["open"]); h=float(c["high"]); l=float(c["low"]); close=float(c["close"])
            rng=max(h-l,1e-12)
            body=min(1.0,abs(close-o)/rng)
            close_pos=min(1.0,max(0.0,(close-l)/rng))
            body_bin=min(3,int(body*4.0))
            close_bin=min(3,int(close_pos*4.0))
            direction="U" if close>o else "D" if close<o else "F"
            parts.append(f"{direction}{body_bin}{close_bin}")
        except (TypeError,ValueError):
            parts.append("F00")
    return ">".join(parts)


def _market_regime(direction,slope_persistent,value_acceptance,level_reclaim,migration_aligned,migration_against,value_position):
    d=str(direction or "").upper()
    if d in {"UP","DOWN"} and migration_against:
        return "CONFLICT"
    if d in {"UP","DOWN"} and value_acceptance and migration_aligned:
        return "ACCEPTED_" + d
    if d in {"UP","DOWN"} and level_reclaim and slope_persistent:
        return "RECLAIM_" + d
    if d in {"UP","DOWN"} and slope_persistent:
        return "TREND_" + d
    vp=str(value_position or "").upper()
    if vp in {"UPPER_VALUE","LOWER_VALUE"}:
        return "ROTATION_" + ("UP" if vp=="UPPER_VALUE" else "DOWN")
    return "BALANCED"


def _decision_time_bucket(ts):
    """Coarse two-hour UAE bucket to reduce time-of-day overfitting."""
    try:
        hour=(datetime.fromtimestamp(float(ts),tz=timezone.utc).hour+4)%24
        return f"UAE_{(hour//2)*2:02d}_{((hour//2)*2+2)%24:02d}"
    except (TypeError,ValueError,OSError):
        return "UAE_UNKNOWN"




def _smma_series(values,period):
    """Return a Wilder-style SMMA sequence without using future candles."""
    n=int(period)
    if n<=0 or len(values)<n:
        return []
    out=[None]*len(values)
    smma=sum(float(x) for x in values[:n])/float(n)
    out[n-1]=smma
    for i in range(n,len(values)):
        smma=((smma*(n-1))+float(values[i]))/float(n)
        out[i]=smma
    return out


def _alligator_confirmation(cs,direction):
    """Confirm AVWAP+VP direction with the configured Alligator.
    
    The terminal shift is a plot shift, not future data. At closed candle t,
    the visible Jaw/Teeth/Lips values correspond to the SMMA values from
    t-8/t-5/t-3 respectively. Only closed M1 candles are used.
    """
    direction=str(direction or "").upper()
    if direction not in {"UP","DOWN"}:
        return {"ready":False,"confirmed":False,"direction":direction}

    medians=[
        (float(c["high"])+float(c["low"]))/2.0
        for c in cs if isinstance(c,dict)
    ]
    required=max(
        ALLIGATOR_JAW_PERIOD+ALLIGATOR_JAW_SHIFT,
        ALLIGATOR_TEETH_PERIOD+ALLIGATOR_TEETH_SHIFT,
        ALLIGATOR_LIPS_PERIOD+ALLIGATOR_LIPS_SHIFT
    )+2
    if len(medians)<required:
        return {
            "ready":False,
            "confirmed":False,
            "direction":direction,
            "reason":"insufficient_closed_m1_history"
        }

    jaw_series=_smma_series(medians,ALLIGATOR_JAW_PERIOD)
    teeth_series=_smma_series(medians,ALLIGATOR_TEETH_PERIOD)
    lips_series=_smma_series(medians,ALLIGATOR_LIPS_PERIOD)
    idx=len(medians)-1

    def shifted(series,shift,at_idx):
        pos=int(at_idx)-int(shift)
        if pos<0 or pos>=len(series) or series[pos] is None:
            return None
        return float(series[pos])

    jaw=shifted(jaw_series,ALLIGATOR_JAW_SHIFT,idx)
    teeth=shifted(teeth_series,ALLIGATOR_TEETH_SHIFT,idx)
    lips=shifted(lips_series,ALLIGATOR_LIPS_SHIFT,idx)
    prev_jaw=shifted(jaw_series,ALLIGATOR_JAW_SHIFT,idx-1)
    prev_teeth=shifted(teeth_series,ALLIGATOR_TEETH_SHIFT,idx-1)
    prev_lips=shifted(lips_series,ALLIGATOR_LIPS_SHIFT,idx-1)

    if None in (jaw,teeth,lips,prev_jaw,prev_teeth,prev_lips):
        return {
            "ready":False,
            "confirmed":False,
            "direction":direction,
            "reason":"alligator_not_ready"
        }

    last_close=float(cs[-1]["close"])
    previous_close=float(cs[-2]["close"])
    if direction=="UP":
        aligned=(
            lips>teeth+ALLIGATOR_MIN_SEPARATION
            and teeth>jaw+ALLIGATOR_MIN_SEPARATION
        )
        slope_votes=sum(
            1 for current,previous in ((lips,prev_lips),(teeth,prev_teeth),(jaw,prev_jaw))
            if current>=previous
        )
        sloping=slope_votes>=2
        price_position=last_close>=lips
        # "Breakout" means a NEW closed-M1 close crossing the outer Alligator
        # line (Lips) from below to above on the direction already chosen by
        # the technical brain. It is event-only: an older breakout does not
        # remain eligible for later cycles.
        breakout=(
            previous_close<=prev_lips
            and last_close>lips
        )
    else:
        aligned=(
            lips<teeth-ALLIGATOR_MIN_SEPARATION
            and teeth<jaw-ALLIGATOR_MIN_SEPARATION
        )
        slope_votes=sum(
            1 for current,previous in ((lips,prev_lips),(teeth,prev_teeth),(jaw,prev_jaw))
            if current<=previous
        )
        sloping=slope_votes>=2
        price_position=last_close<=lips
        breakout=(
            previous_close>=prev_lips
            and last_close<lips
        )

    spread=abs(lips-teeth)+abs(teeth-jaw)
    prev_spread=abs(prev_lips-prev_teeth)+abs(prev_teeth-prev_jaw)
    spread_ratio=(
        spread/max(prev_spread,1e-12) if prev_spread>0.0 else 1.0
    )
    latest_candle_close_ts=float(cs[-1]["time"])+ONE_MINUTE
    closed_age=max(0.0,time.time()-latest_candle_close_ts)
    timing_ok=(
        closed_age<=ALLIGATOR_TIMING_MAX_AGE_SECONDS
        and spread_ratio>=ALLIGATOR_MIN_SPREAD_RATIO
    )
    confirmed=bool(aligned and sloping and price_position and timing_ok)

    return {
        "ready":True,
        "confirmed":confirmed,
        "timing_ok":bool(timing_ok),
        "direction":direction,
        "jaw":jaw,
        "teeth":teeth,
        "lips":lips,
        "prev_jaw":prev_jaw,
        "prev_teeth":prev_teeth,
        "prev_lips":prev_lips,
        "aligned":bool(aligned),
        "sloping":bool(sloping),
        "price_position":bool(price_position),
        "breakout":bool(breakout),
        "breakout_confirmed":bool(breakout and aligned and sloping and timing_ok),
        "breakout_direction":direction if breakout else "",
        "breakout_candle_ts":int(cs[-1]["time"]) if breakout else 0,
        "breakout_previous_close":float(previous_close),
        "breakout_current_close":float(last_close),
        "spread":float(spread),
        "prev_spread":float(prev_spread),
        "spread_ratio":float(spread_ratio),
        "latest_closed_candle_ts":int(cs[-1]["time"]),
        "closed_age_seconds":float(closed_age),
        "timing_max_age_seconds":ALLIGATOR_TIMING_MAX_AGE_SECONDS,
        "min_spread_ratio":ALLIGATOR_MIN_SPREAD_RATIO,
        "periods":"13/8,8/5,5/3",
        "confirmation":"CONFIRMED" if confirmed else "REJECTED",
    }


def detect_alligator_breakout(candles, now=None):
    """Return a NEW closed-M1 Alligator breakout event, or None.

    This is a lightweight event detector for the scheduler's watchlist.
    It does not choose strategy direction, does not use future candles, and
    does not run AVWAP/VP, OTC structure, BB, or AI checks. Those existing
    confirmations remain authoritative after an event is detected.
    """
    cs=_closed_1m(candles, time.time() if now is None else float(now))
    if len(cs)<max(
        ALLIGATOR_JAW_PERIOD+ALLIGATOR_JAW_SHIFT,
        ALLIGATOR_TEETH_PERIOD+ALLIGATOR_TEETH_SHIFT,
        ALLIGATOR_LIPS_PERIOD+ALLIGATOR_LIPS_SHIFT,
    )+2:
        return None

    up=_alligator_confirmation(cs,"UP")
    down=_alligator_confirmation(cs,"DOWN")
    events=[]
    for item in (up,down):
        if not isinstance(item,dict):
            continue
        if bool(item.get("breakout")) and bool(item.get("breakout_confirmed")):
            events.append(item)
    if not events:
        return None
    # A single candle should not qualify as both directions; preserve the
    # deterministic order in case numerical equality occurs at a boundary.
    events.sort(key=lambda x: (
        1 if str(x.get("direction") or "").upper()=="UP" else 0,
        float(x.get("closed_age_seconds") or 9999.0)
    ), reverse=True)
    event=events[0]
    return {
        "direction":str(event.get("direction") or "").upper(),
        "breakout_confirmed":True,
        "breakout_candle_ts":int(event.get("breakout_candle_ts") or cs[-1]["time"]),
        "previous_close":float(event.get("breakout_previous_close") or cs[-2]["close"]),
        "current_close":float(event.get("breakout_current_close") or cs[-1]["close"]),
        "jaw":event.get("jaw"),
        "teeth":event.get("teeth"),
        "lips":event.get("lips"),
        "aligned":bool(event.get("aligned")),
        "sloping":bool(event.get("sloping")),
        "price_position":bool(event.get("price_position")),
        "timing_ok":bool(event.get("timing_ok")),
        "spread_ratio":float(event.get("spread_ratio") or 0.0),
        "closed_age_seconds":float(event.get("closed_age_seconds") or 9999.0),
        "periods":event.get("periods","13/8,8/5,5/3"),
    }


def _bollinger_confirmation(candles, direction, period=18, multiplier=2.0):
    """Return a zero-network M1 Bollinger 18/2 confirmation layer.
    
    Bollinger is confirmation only: it never chooses or flips the AVWAP+VP
    direction and it never hard-blocks a live candidate. This keeps the
    3-minute scheduler and signal cadence independent of the confirmation.
    """
    try:
        n=int(period)
        k=float(multiplier)
    except (TypeError,ValueError):
        n=18
        k=2.0
    n=max(18,min(18,n))
    k=2.0

    closes=[_f(x.get("close"),0.0) for x in (candles or []) if isinstance(x,dict)]
    closes=[x for x in closes if x>0.0]
    if len(closes)<n:
        return {
            "bb_period":n,
            "bb_multiplier":k,
            "bb_ready":False,
            "bb_confirmation":"UNAVAILABLE",
            "bb_basis":None,
            "bb_upper":None,
            "bb_lower":None,
            "bb_bandwidth":None,
            "bb_bandwidth_expanding":False,
        }

    window=closes[-n:]
    mean=sum(window)/n
    variance=sum((x-mean)*(x-mean) for x in window)/n
    stdev=variance**0.5
    upper=mean+(k*stdev)
    lower=mean-(k*stdev)

    prev_window=closes[-(n+1):-1] if len(closes)>=n+1 else []
    prev_mean=(sum(prev_window)/n) if len(prev_window)==n else mean
    prev_var=(
        sum((x-prev_mean)*(x-prev_mean) for x in prev_window)/n
        if len(prev_window)==n else variance
    )
    prev_stdev=max(0.0,prev_var**0.5)
    prev_upper=prev_mean+(k*prev_stdev)
    prev_lower=prev_mean-(k*prev_stdev)

    bandwidth=(upper-lower)/max(abs(mean),1e-12)
    prev_bandwidth=(prev_upper-prev_lower)/max(abs(prev_mean),1e-12)
    bandwidth_expanding=bandwidth>prev_bandwidth

    last_close=window[-1]
    direction=str(direction or "").upper()
    if direction=="UP":
        aligned=(last_close>=mean and upper>=prev_upper and (bandwidth_expanding or last_close>=upper*0.995))
        state="ALIGNED" if aligned else "NEUTRAL"
    elif direction=="DOWN":
        aligned=(last_close<=mean and lower<=prev_lower and (bandwidth_expanding or last_close<=lower*1.005))
        state="ALIGNED" if aligned else "NEUTRAL"
    else:
        state="UNAVAILABLE"

    return {
        "bb_period":n,
        "bb_multiplier":k,
        "bb_ready":True,
        "bb_confirmation":state,
        "bb_basis":mean,
        "bb_upper":upper,
        "bb_lower":lower,
        "bb_bandwidth":bandwidth,
        "bb_bandwidth_expanding":bandwidth_expanding,
        "bb_last_close":last_close,
        "bb_previous_basis":prev_mean,
        "bb_previous_upper":prev_upper,
        "bb_previous_lower":prev_lower,
    }

def _is_otc_asset(asset):
    """Return True only for assets explicitly labelled as OTC."""
    if not isinstance(asset,dict):
        return False
    values=[]
    for key in ("pair","symbol","instrument","title","display_name","displayName","name","mode","market_mode"):
        v=asset.get(key)
        if isinstance(v,str) and v.strip():
            values.append(v.strip().upper())
    for value in values:
        compact=re.sub(r"[^A-Z0-9]+","_",value).strip("_")
        if compact.endswith("_OTC") or value.endswith(" OTC"):
            return True
        if re.search(r"(^|[_\-\s])OTC($|[_\-\s])",value):
            return True
    return False


def _otc_range(c):
    return max(float(c["high"])-float(c["low"]),1e-12)


def _otc_body_ratio(c):
    return abs(float(c["close"])-float(c["open"]))/_otc_range(c)


def _otc_median(values):
    xs=sorted(float(x) for x in values if float(x)>0.0)
    if not xs:
        return 0.0
    n=len(xs)
    mid=n//2
    return xs[mid] if n%2 else (xs[mid-1]+xs[mid])/2.0


FIVE_MINUTES=300

# The legacy 5M cadence fallback was introduced to keep wall-clock slots populated,
# but it can use a completed 5M bar that is too old for a 1M/2M production entry.
# Keep it opt-in for future 5M-expiry validation; production live signals remain
# on the strict M1 structure path until the 5M entry timing is independently validated.
ALLOW_5M_CADENCE_FALLBACK = os.getenv("ALLOW_5M_CADENCE_FALLBACK","0").strip().lower() in {"1","true","yes","on"}
FIVE_MINUTE_MAX_SETUP_AGE_SECONDS = max(
    60.0,
    min(180.0,float(os.getenv("FIVE_MINUTE_MAX_SETUP_AGE_SECONDS","120") or 120.0))
)

def _complete_5m_blocks(cs,now=None):
    """Build exact closed 5-minute bars from complete 1-minute candles only."""
    now=time.time() if now is None else float(now)
    groups={}
    for c in cs:
        minute=int(c["time"])
        bucket=(minute//FIVE_MINUTES)*FIVE_MINUTES
        if bucket+FIVE_MINUTES>now-CLOSE_GRACE_SECONDS:
            continue
        groups.setdefault(bucket,[]).append(c)

    out=[]
    for bucket,bars in sorted(groups.items()):
        bars=sorted(bars,key=lambda x:x["time"])
        expected=[bucket+i*ONE_MINUTE for i in range(5)]
        if [int(x["time"]) for x in bars]!=expected:
            continue
        out.append({
            "time":bucket,
            "open":bars[0]["open"],
            "high":max(x["high"] for x in bars),
            "low":min(x["low"] for x in bars),
            "close":bars[-1]["close"],
            "volume":sum(x.get("volume",0.0) for x in bars),
        })
    return out


def _ema_last_value(values,period):
    xs=[float(x) for x in values if isfinite(float(x))]
    if len(xs)<period:
        return None
    k=2.0/(period+1.0)
    ema=sum(xs[:period])/period
    for x in xs[period:]:
        ema=(x*k)+(ema*(1.0-k))
    return ema


def _five_minute_cadence_setup(cs,primary_bias=None,now=None):
    """
    Deterministic 5M continuation path used only when the stricter 1M
    BOS/retest detector has no setup. It never uses a forming candle.
    """
    now=time.time() if now is None else float(now)
    blocks=_complete_5m_blocks(cs,now)
    if len(blocks)<12:
        return None

    closes=[float(x["close"]) for x in blocks]
    last=blocks[-1]
    ema9=_ema_last_value(closes,9)
    ema21=_ema_last_value(closes,21)
    if ema9 is None or ema21 is None:
        return None

    ranges=[_otc_range(x) for x in blocks[-9:-1]]
    baseline=max(_otc_median(ranges),1e-12)
    last_range=_otc_range(last)
    body_ratio=_otc_body_ratio(last)

    momentum_up=float(last["close"])>float(blocks[-4]["close"])
    momentum_down=float(last["close"])<float(blocks[-4]["close"])

    prior_high=max(float(x["high"]) for x in blocks[-4:-1])
    prior_low=min(float(x["low"]) for x in blocks[-4:-1])
    breakout_up=float(last["close"])>prior_high and float(last["close"])>float(last["open"])
    breakout_down=float(last["close"])<prior_low and float(last["close"])<float(last["open"])

    higher_closes=float(blocks[-1]["close"])>float(blocks[-2]["close"])>=float(blocks[-3]["close"])
    higher_lows=float(blocks[-1]["low"])>=float(blocks[-2]["low"])>=float(blocks[-3]["low"])
    lower_closes=float(blocks[-1]["close"])<float(blocks[-2]["close"])<=float(blocks[-3]["close"])
    lower_highs=float(blocks[-1]["high"])<=float(blocks[-2]["high"])<=float(blocks[-3]["high"])

    trend_up=float(last["close"])>float(ema9)>=float(ema21) and (higher_closes or higher_lows)
    trend_down=float(last["close"])<float(ema9)<=float(ema21) and (lower_closes or lower_highs)

    retest_up=False
    retest_down=False
    if len(blocks)>=7:
        for i in range(max(4,len(blocks)-5),len(blocks)-1):
            level_up=max(float(x["high"]) for x in blocks[i-3:i])
            level_down=min(float(x["low"]) for x in blocks[i-3:i])
            b=blocks[i]
            if float(b["close"])>level_up and float(b["close"])>float(b["open"]):
                if any(
                    float(r["low"])<=level_up<=float(r["high"])
                    and float(r["close"])>=level_up
                    for r in blocks[i+1:]
                ):
                    retest_up=True
            if float(b["close"])<level_down and float(b["close"])<float(b["open"]):
                if any(
                    float(r["low"])<=level_down<=float(r["high"])
                    and float(r["close"])<=level_down
                    for r in blocks[i+1:]
                ):
                    retest_down=True

    fvg_up=any(
        float(blocks[i]["low"])>float(blocks[i-2]["high"])
        for i in range(max(2,len(blocks)-4),len(blocks))
    )
    fvg_down=any(
        float(blocks[i]["high"])<float(blocks[i-2]["low"])
        for i in range(max(2,len(blocks)-4),len(blocks))
    )

    up_score=0
    down_score=0
    if primary_bias=="BULLISH": up_score+=6
    if primary_bias=="BEARISH": down_score+=6
    if float(last["close"])>float(ema9): up_score+=5
    if float(last["close"])<float(ema9): down_score+=5
    if float(ema9)>float(ema21): up_score+=4
    if float(ema9)<float(ema21): down_score+=4
    if momentum_up: up_score+=5
    if momentum_down: down_score+=5
    if breakout_up: up_score+=6
    if breakout_down: down_score+=6
    if higher_closes or higher_lows: up_score+=3
    if lower_closes or lower_highs: down_score+=3
    if body_ratio>=0.45 and float(last["close"])>float(last["open"]): up_score+=2
    if body_ratio>=0.45 and float(last["close"])<float(last["open"]): down_score+=2
    if last_range>=baseline*1.05 and float(last["close"])>float(last["open"]): up_score+=2
    if last_range>=baseline*1.05 and float(last["close"])<float(last["open"]): down_score+=2
    if retest_up: up_score+=3
    if retest_down: down_score+=3
    if fvg_up: up_score+=2
    if fvg_down: down_score+=2

    if primary_bias=="BULLISH" and up_score>=down_score:
        direction="UP"
    elif primary_bias=="BEARISH" and down_score>=up_score:
        direction="DOWN"
    else:
        direction="UP" if up_score>down_score else "DOWN"

    derived_bias="BULLISH" if direction=="UP" else "BEARISH"
    # A 5M fallback may never override the authoritative 15M bias.
    if primary_bias in {"BULLISH","BEARISH"} and derived_bias != primary_bias:
        return None

    closed_last_end=float(last["time"])+FIVE_MINUTES
    setup_age_seconds=max(0.0,now-closed_last_end)
    if setup_age_seconds > FIVE_MINUTE_MAX_SETUP_AGE_SECONDS:
        return None

    directional_ok=(up_score>down_score) if direction=="UP" else (down_score>up_score)
    momentum_ok=momentum_up if direction=="UP" else momentum_down
    structure_ok=(
        (breakout_up or higher_closes or higher_lows)
        if direction=="UP"
        else (breakout_down or lower_closes or lower_highs)
    )
    entry_ok=(
        float(last["close"])>=float(last["open"])
        if direction=="UP"
        else float(last["close"])<=float(last["open"])
    )
    # The 5M bar is the authoritative entry confirmation for the 5M cadence path.
    # A single opposite 1M candle must not invalidate an otherwise aligned 5M setup.
    if not (directional_ok and momentum_ok and structure_ok and entry_ok):
        return None

    evidence_score=78.0
    evidence_score+=4.0 if primary_bias in {"BULLISH","BEARISH"} else 0.0
    evidence_score+=4.0 if (breakout_up or breakout_down) else 0.0
    evidence_score+=3.0 if (trend_up if direction=="UP" else trend_down) else 0.0
    evidence_score+=3.0 if (retest_up if direction=="UP" else retest_down) else 0.0
    evidence_score+=2.0 if (fvg_up if direction=="UP" else fvg_down) else 0.0
    evidence_score+=2.0 if last_range>=baseline*1.05 else 0.0
    confidence=min(96,max(80,int(round(evidence_score))))

    return {
        "direction":direction,
        "bos_level":float(prior_high if direction=="UP" else prior_low),
        "bos_candle_ts":int(last["time"]),
        "retest_candle_ts":int(last["time"]),
        "confirmation_candle_ts":int(last["time"]),
        "entry_candle_ts":int(cs[-1]["time"]),
        "bos_range":float(last_range),
        "baseline_range":float(baseline),
        "bos_body_ratio":float(body_ratio),
        "displacement_confirmed":bool(last_range>=baseline*1.05 and body_ratio>=0.35),
        "retest_confirmed":bool(retest_up if direction=="UP" else retest_down),
        "hold_confirmed":True,
        "confirmation_candle_confirmed":True,
        "entry_continuation_confirmed":True,
        "sequence":(
            "5M_BREAKOUT_RETEST_CONTINUATION"
            if (breakout_up or breakout_down or retest_up or retest_down)
            else "5M_STRUCTURE_CONTINUATION"
        ),
        "five_minute_directional_ok":True,
        "five_minute_structure_ok":True,
        "five_minute_momentum_ok":True,
        "five_minute_entry_candle_ok":bool(entry_ok),
        "five_minute_trend_up":bool(trend_up),
        "five_minute_trend_down":bool(trend_down),
        "five_minute_breakout":bool(breakout_up or breakout_down),
        "five_minute_retest":bool(retest_up or retest_down),
        "five_minute_fvg":bool(fvg_up if direction=="UP" else fvg_down),
        "five_minute_ema9":float(ema9),
        "five_minute_ema21":float(ema21),
        "five_minute_momentum":float(last["close"]-blocks[-4]["close"]),
        "five_minute_last_range":float(last_range),
        "five_minute_baseline_range":float(baseline),
        "five_minute_score_up":int(up_score),
        "five_minute_score_down":int(down_score),
        "five_minute_confidence":int(confidence),
        "five_minute_primary_bias":str(primary_bias or derived_bias or "NEUTRAL"),
        "five_minute_last_closed_ts":int(closed_last_end),
        "five_minute_setup_age_seconds":float(setup_age_seconds),
    }


def _otc_15m_bias(blocks):
    """Use only complete closed 15M blocks; never include a forming block."""
    if len(blocks)<3:
        return None,0
    b1,b2,b3=blocks[-3:]
    bull_votes=sum((
        1 if float(b3["close"])>float(b2["close"]) else 0,
        1 if float(b3["high"])>=float(b2["high"]) and float(b3["low"])>=float(b2["low"]) else 0,
        1 if float(b2["close"])>float(b1["close"]) else 0,
    ))
    bear_votes=sum((
        1 if float(b3["close"])<float(b2["close"]) else 0,
        1 if float(b3["high"])<=float(b2["high"]) and float(b3["low"])<=float(b2["low"]) else 0,
        1 if float(b2["close"])<float(b1["close"]) else 0,
    ))
    if bull_votes>=2 and bull_votes>bear_votes:
        return "BULLISH",bull_votes
    if bear_votes>=2 and bear_votes>bull_votes:
        return "BEARISH",bear_votes
    return None,max(bull_votes,bear_votes)


def _otc_structure_setup(cs,direction):
    """
    Detect a recent, fully closed PRO Structure Continuation sequence.

    The strategy itself is unchanged:
      15M bias -> 1M BOS -> displacement -> retest -> hold -> confirmation -> entry.

    The old detector required the confirmation candle to be the immediately latest
    closed candle and allowed only a two-candle BOS/retest spacing. That made valid
    recent structures disappear between the 3-minute scan boundaries. This version
    searches a bounded recent window while keeping every structural condition strict.
    """
    if len(cs)<10:
        return None

    d=str(direction or "").upper()
    if d not in {"UP","DOWN"}:
        return None

    latest_idx=len(cs)-1
    # Confirmation may be one of the most recent 1-minute closed candles. It cannot
    # be older than four bars, so the setup never becomes a stale historical signal.
    min_confirmation_idx=max(5,latest_idx-4)

    for confirmation_idx in range(latest_idx,min_confirmation_idx-1,-1):
        confirmation=cs[confirmation_idx]

        # Retest must occur shortly before confirmation.
        for retest_idx in range(max(5,confirmation_idx-3),confirmation_idx):
            retest=cs[retest_idx]

            # BOS must occur shortly before retest; no large temporal gaps.
            for bos_idx in range(max(5,retest_idx-3),retest_idx):
                if confirmation_idx-bos_idx>7:
                    continue

                prior=cs[bos_idx-5:bos_idx]
                if len(prior)<5:
                    continue

                prior_range=[_otc_range(x) for x in prior]
                baseline=max(_otc_median(prior_range),1e-12)
                bos=cs[bos_idx]
                bos_range=_otc_range(bos)
                bos_body=_otc_body_ratio(bos)

                displacement=(
                    bos_body>=0.55
                    and bos_range>=baseline*1.15
                )
                if not displacement:
                    continue

                if d=="UP":
                    swing=max(float(x["high"]) for x in prior)
                    bos_ok=(
                        float(bos["close"])>swing
                        and float(bos["close"])>float(bos["open"])
                    )
                    touched=(
                        float(retest["low"])<=swing<=float(retest["high"])
                    )
                    hold=(
                        touched
                        and float(retest["close"])>=swing
                        and float(retest["close"])>float(retest["open"])
                    )
                    confirmation_ok=(
                        float(confirmation["close"])>float(confirmation["open"])
                        and float(confirmation["close"])>float(retest["close"])
                        and _otc_body_ratio(confirmation)>=0.40
                    )
                else:
                    swing=min(float(x["low"]) for x in prior)
                    bos_ok=(
                        float(bos["close"])<swing
                        and float(bos["close"])<float(bos["open"])
                    )
                    touched=(
                        float(retest["low"])<=swing<=float(retest["high"])
                    )
                    hold=(
                        touched
                        and float(retest["close"])<=swing
                        and float(retest["close"])<float(retest["open"])
                    )
                    confirmation_ok=(
                        float(confirmation["close"])<float(confirmation["open"])
                        and float(confirmation["close"])<float(retest["close"])
                        and _otc_body_ratio(confirmation)>=0.40
                    )

                if not (bos_ok and confirmation_ok and hold):
                    continue

                # At the signal decision, the latest closed candle must still be
                # directionally consistent with the confirmed structure. When the
                # confirmation itself is latest, this is checked against the
                # previous closed candle; otherwise the latest candle must continue
                # beyond the confirmation close without needing a new indicator.
                latest=cs[latest_idx]
                if d=="UP":
                    if confirmation_idx==latest_idx:
                        entry_continuation=(
                            float(latest["close"])>=float(latest["open"])
                            and float(latest["close"])>float(cs[latest_idx-1]["close"])
                        )
                    else:
                        entry_continuation=(
                            float(latest["close"])>=float(latest["open"])
                            and float(latest["close"])>=float(confirmation["close"])
                            and _otc_body_ratio(latest)>=0.20
                        )
                else:
                    if confirmation_idx==latest_idx:
                        entry_continuation=(
                            float(latest["close"])<=float(latest["open"])
                            and float(latest["close"])<float(cs[latest_idx-1]["close"])
                        )
                    else:
                        entry_continuation=(
                            float(latest["close"])<=float(latest["open"])
                            and float(latest["close"])<=float(confirmation["close"])
                            and _otc_body_ratio(latest)>=0.20
                        )

                if not entry_continuation:
                    continue

                return {
                    "bos_level":float(swing),
                    "bos_candle_ts":int(bos["time"]),
                    "retest_candle_ts":int(retest["time"]),
                    "confirmation_candle_ts":int(confirmation["time"]),
                    "entry_candle_ts":int(latest["time"]),
                    "bos_range":float(bos_range),
                    "baseline_range":float(baseline),
                    "bos_body_ratio":float(bos_body),
                    "displacement_confirmed":True,
                    "retest_confirmed":True,
                    "hold_confirmed":True,
                    "confirmation_candle_confirmed":True,
                    "entry_continuation_confirmed":True,
                    "sequence":f"BOS_{d}_DISPLACEMENT_RETEST_HOLD_CONFIRM",
                }
    return None
def analyze_otc_asset(
    asset,
    candles,
    price=None,
    forced_strategy=None,
    learning_campaign=False,
    require_high_volume=True,
):
    """Analyze OTC assets only with the PRO Structure Continuation strategy."""
    forced=str(forced_strategy or "").upper().strip()
    if forced and forced!=OTC_STRATEGY:
        return None

    now=time.time()
    pair=str(asset.get("pair") or "")
    cs=_closed_1m(candles,now)
    if len(cs)<MIN_CLOSED_CANDLES:
        _diag(pair,"otc_history_short",closed=len(cs),required=MIN_CLOSED_CANDLES)
        return None

    blocks=_complete_15m_blocks(cs,now)
    bias,bias_votes=_otc_15m_bias(blocks)
    cadence_fallback=False

    # Prefer the authoritative closed-15M bias. If a cycle has no valid 15M
    # bias yet, allow the deterministic 5M continuation lane to establish a
    # directional bias from closed 5M structure/momentum rather than starving
    # the wall-clock 5-minute signal slot.
    if bias not in {"BULLISH","BEARISH"}:
        if not ALLOW_5M_CADENCE_FALLBACK:
            _diag(pair,"otc_15m_bias_rejected",bias=bias,bias_votes=bias_votes,blocks=len(blocks),detail="5m_cadence_fallback_disabled")
            return None
        cadence_setup=_five_minute_cadence_setup(cs,None,now=now)
        if not cadence_setup:
            _diag(pair,"otc_15m_bias_rejected",bias=bias,bias_votes=bias_votes,blocks=len(blocks))
            return None
        setup=cadence_setup
        cadence_fallback=True
        direction=str(setup.get("direction") or "").upper()
        if direction not in {"UP","DOWN"}:
            _diag(pair,"otc_5m_fallback_invalid_direction",direction=direction)
            return None
        bias="BULLISH" if direction=="UP" else "BEARISH"
        bias_votes=0
    else:
        direction="UP" if bias=="BULLISH" else "DOWN"
        setup=_otc_structure_setup(cs,direction)
        if not setup:
            if not ALLOW_5M_CADENCE_FALLBACK:
                _diag(pair,"otc_structure_sequence_rejected",direction=direction,detail="strict_m1_required")
                return None
            cadence_setup=_five_minute_cadence_setup(cs,bias,now=now)
            if not cadence_setup:
                _diag(pair,"otc_structure_sequence_rejected",direction=direction)
                return None
            setup=cadence_setup
            cadence_fallback=True
            direction=str(setup.get("direction") or direction).upper()
            derived_bias="BULLISH" if direction=="UP" else "BEARISH"
            if derived_bias != bias:
                _diag(pair,"otc_5m_bias_conflict_rejected",direction=direction,primary_bias=bias)
                return None

    # The strategy itself is structure/candle based. Broker-reported volume is
    # intentionally not used to create the OTC decision. The final scheduler
    # activity gate can still require fresh observed tick activity at entry.
    ranges=[_otc_range(x) for x in cs[-8:-1]]
    latest_range=_otc_range(cs[-1])
    avg_recent=_otc_median(ranges)
    displacement_strength=min(
        1.0,
        float(setup["bos_range"])/max(float(setup["baseline_range"]),1e-12)
    )
    score=90.0
    score += min(4.0,float(max(0,bias_votes-1))*2.0)
    score += min(3.0,max(0.0,(displacement_strength-1.15)*4.0))
    score += 2.0 if setup["hold_confirmed"] else 0.0
    score += 2.0 if setup["confirmation_candle_confirmed"] else 0.0
    if avg_recent>0 and latest_range>=avg_recent:
        score += 1.0
    confidence=min(99,max(0,int(round(score))))

    last=cs[-1]
    previous=cs[-2]
    # Alligator is an entry-timing event here only. It never changes the OTC
    # structure direction; the boundary delivery gate decides whether a NEW
    # breakout exists on the latest closed M1 candle.
    alligator=_alligator_confirmation(cs,direction)
    # The structure detector already checked the exact closed-candle continuation
    # in the same bounded recent window. Keep the flag explicit for final gating.
    m1_continuation_ok=bool(setup.get("entry_continuation_confirmed"))

    # Final freshness/alignment guard. A live OTC signal may never use stale
    # structural evidence, and a 5M fallback may not disagree with the 15M bias.
    latest_closed_ts=int(cs[-1]["time"])
    if cadence_fallback:
        five_bias=str(setup.get("five_minute_primary_bias") or bias).upper()
        expected_bias="BULLISH" if direction=="UP" else "BEARISH"
        if five_bias != expected_bias or five_bias != str(bias).upper():
            _diag(pair,"otc_5m_bias_conflict_rejected",direction=direction,five_bias=five_bias,bias=bias)
            return None
        age=float(setup.get("five_minute_setup_age_seconds") or 9999.0)
        if age > FIVE_MINUTE_MAX_SETUP_AGE_SECONDS:
            _diag(pair,"otc_5m_setup_stale",age_seconds=age,max_age=FIVE_MINUTE_MAX_SETUP_AGE_SECONDS)
            return None
    else:
        bos_age=max(0.0,float(latest_closed_ts)-float(setup.get("bos_candle_ts") or latest_closed_ts))
        confirmation_age=max(0.0,float(latest_closed_ts)-float(setup.get("confirmation_candle_ts") or latest_closed_ts))
        if bos_age > 5*ONE_MINUTE or confirmation_age > 4*ONE_MINUTE:
            _diag(pair,"otc_m1_structure_stale",bos_age_seconds=bos_age,confirmation_age_seconds=confirmation_age)
            return None

    # The complete strategy sequence is the authoritative live gate.
    exact_live_setup=bool(
        bias in {"BULLISH","BEARISH"}
        and (setup["displacement_confirmed"] if not cadence_fallback else setup.get("five_minute_directional_ok"))
        and (setup["retest_confirmed"] if not cadence_fallback else setup.get("five_minute_structure_ok"))
        and setup["hold_confirmed"]
        and setup["confirmation_candle_confirmed"]
        and m1_continuation_ok
    )
    if not exact_live_setup:
        _diag(
            pair,"otc_exact_setup_rejected",direction=direction,
            m1_continuation_ok=m1_continuation_ok,cadence_fallback=cadence_fallback
        )
        return None

    anchor_ts=int(blocks[-1]["time"])
    features={
        "otc_strategy":True,
        "otc_market_bias":bias,
        "otc_bias_votes":int(bias_votes),
        "otc_bos_confirmed":True,
        "otc_bos_level":float(setup["bos_level"]),
        "otc_bos_candle_ts":int(setup["bos_candle_ts"]),
        "otc_displacement_confirmed":True,
        "otc_displacement_strength":round(displacement_strength,4),
        "otc_baseline_range":float(setup["baseline_range"]),
        "otc_bos_range":float(setup["bos_range"]),
        "otc_bos_body_ratio":round(float(setup["bos_body_ratio"]),4),
        "otc_retest_confirmed":True,
        "otc_hold_confirmed":True,
        "otc_confirmation_candle_confirmed":True,
        "otc_confirmation_candle_ts":int(setup["confirmation_candle_ts"]),
        "otc_entry_candle_ts":int(setup.get("entry_candle_ts") or last["time"]),
        "otc_entry_continuation_confirmed":bool(setup.get("entry_continuation_confirmed")),
        "otc_sequence":setup["sequence"],
        "m1_continuation_ok":m1_continuation_ok,
        "exact_live_setup":True,
        "five_minute_mode":"CADENCE_CONTINUATION_V1" if cadence_fallback else "STRICT_1M_STRUCTURE_V1",
        "five_minute_cadence_fallback":bool(cadence_fallback),
        "five_minute_directional_ok":bool(setup.get("five_minute_directional_ok",True)),
        "five_minute_structure_ok":bool(setup.get("five_minute_structure_ok",True)),
        "five_minute_momentum_ok":bool(setup.get("five_minute_momentum_ok",True)),
        "five_minute_entry_candle_ok":bool(setup.get("five_minute_entry_candle_ok",True)),
        "five_minute_trend_up":bool(setup.get("five_minute_trend_up",False)),
        "five_minute_trend_down":bool(setup.get("five_minute_trend_down",False)),
        "five_minute_breakout":bool(setup.get("five_minute_breakout",False)),
        "five_minute_retest":bool(setup.get("five_minute_retest",False)),
        "five_minute_fvg":bool(setup.get("five_minute_fvg",False)),
        "five_minute_ema9":float(setup.get("five_minute_ema9") or 0.0),
        "five_minute_ema21":float(setup.get("five_minute_ema21") or 0.0),
        "five_minute_momentum":float(setup.get("five_minute_momentum") or 0.0),
        "five_minute_score_up":int(setup.get("five_minute_score_up") or 0),
        "five_minute_score_down":int(setup.get("five_minute_score_down") or 0),
        "five_minute_primary_bias":str(setup.get("five_minute_primary_bias") or bias),
        "five_minute_last_closed_ts":int(setup.get("five_minute_last_closed_ts") or 0),
        "five_minute_setup_age_seconds":float(setup.get("five_minute_setup_age_seconds") or 0.0),
        "analysis_timeframe":"5M" if cadence_fallback else "1M",
        "volume_mode":"OTC_OBSERVED_TICK_ACTIVITY_AT_ENTRY",
        "volume_quality":"N/A_STRUCTURE_STRATEGY",
        "real_volume_verified":False,
        "high_volume_confirmed":False,
        "high_volume_gate_pending":True,
        "volume_gate_mode":"OTC_TICK_ACTIVITY_ENTRY_GATE",
        "value_position":"OTC_STRUCTURE",
        "value_area_acceptance":True,
        "level_reclaim":False,
        "slope_persistent":True,
        "profile_poc_migration_norm":0.0,
        "anchored_vwap":None,
        "volume_profile_poc":None,
        "volume_profile_vah":None,
        "volume_profile_val":None,
        "m1_sequence_signature":_m1_sequence_signature(cs,6),
        "market_regime":"OTC_TREND_CONTINUATION_"+direction,
        "decision_time_bucket":_decision_time_bucket(last["time"]),
        "alligator_confirmed":bool(alligator.get("confirmed")),
        "alligator_alignment_ready":bool(alligator.get("ready")),
        "alligator_aligned":bool(alligator.get("aligned")),
        "alligator_sloping":bool(alligator.get("sloping")),
        "alligator_price_position":bool(alligator.get("price_position")),
        "alligator_timing_ok":bool(alligator.get("timing_ok")),
        "alligator_jaw":alligator.get("jaw"),
        "alligator_teeth":alligator.get("teeth"),
        "alligator_lips":alligator.get("lips"),
        "alligator_prev_jaw":alligator.get("prev_jaw"),
        "alligator_prev_teeth":alligator.get("prev_teeth"),
        "alligator_prev_lips":alligator.get("prev_lips"),
        "alligator_breakout":bool(alligator.get("breakout")),
        "alligator_breakout_confirmed":bool(alligator.get("breakout_confirmed")),
        "alligator_breakout_direction":alligator.get("breakout_direction"),
        "alligator_breakout_candle_ts":alligator.get("breakout_candle_ts"),
        "alligator_breakout_previous_close":alligator.get("breakout_previous_close"),
        "alligator_breakout_current_close":alligator.get("breakout_current_close"),
        "alligator_latest_closed_candle_ts":alligator.get("latest_closed_candle_ts"),
        "alligator_closed_age_seconds":alligator.get("closed_age_seconds"),
        "alligator_periods":alligator.get("periods","13/8,8/5,5/3"),
        "alligator_min_spread_ratio":alligator.get("min_spread_ratio"),
    }

    return {
        "pair":pair,
        "display_name":str(
            asset.get("display_name") or asset.get("title") or
            asset.get("name") or asset.get("pair") or ""
        ),
        "direction":direction,
        "confidence":confidence,
        "strategy":OTC_STRATEGY,
        "expiry_minutes":1,
        "pattern":"PRO_OTC_STRUCTURE_CONTINUATION",
        "trend_15m":f"OTC_{bias}",
        "structure_1m":(
            setup["sequence"] if not cadence_fallback
            else str(setup["sequence"]).replace("5M_","")
        ),
        "market_quality":float(score),
        "confluence_score":float(score),
        "direction_agreement":1.0,
        "value_area_acceptance":True,
        "reason":(
            f"OTC {bias} 15M; M1 BOS level={setup['bos_level']:.8f}; "
            f"displacement={setup['displacement_confirmed']}; "
            f"retest={setup['retest_confirmed']}; hold={setup['hold_confirmed']}; "
            f"confirmation={setup['confirmation_candle_confirmed']}; "
            f"M1_continuation={m1_continuation_ok}; "
            f"entry activity=observed Event-1 tick gate."
        ),
        "indicator_features":features,
        "indicators":features,
        "entry_candle_ts":last["time"],
        "closed_1m_ts":last["time"],
        "closed_15m_ts":anchor_ts,
        "decision_candle_closed":True,
        "price":float(last["close"]),
        "five_minute_eligible":True,
        "self_strategy_version":"OTC_STRUCTURE_5M_V2" if cadence_fallback else "OTC_STRUCTURE_V1",
        "strategy_candidates":[{
            "strategy":OTC_STRATEGY,
            "direction":direction,
            "score":confidence,
            "expiry_minutes":1,
            "self_strategy_version":"OTC_STRUCTURE_V1",
        }],
        "strategy_audit":[{
            "strategy":OTC_STRATEGY,
            "active_for_live":True,
            "otc_only":True,
            "up_qualified":direction=="UP",
            "down_qualified":direction=="DOWN",
        }],
        "strategy_audit_count":1,
        "indicator_audit_scope":"OTC_15M_BIAS_1M_BOS_DISPLACEMENT_RETEST_HOLD_CONFIRMATION",
        "m1_sequence_signature":features["m1_sequence_signature"],
        "market_regime":features["market_regime"],
        "decision_time_bucket":features["decision_time_bucket"],
    }


def analyze_asset(
    asset,
    candles,
    price=None,
    forced_strategy=None,
    learning_campaign=False,
    require_high_volume=True,
):
    """Return one deterministic asset-class-specific live candidate or None.

    OTC routing occurs before the REAL-asset AVWAP analysis below.
    """
    forced=str(forced_strategy or "").upper().strip()
    if forced and forced not in LIVE_STRATEGIES:
        return None

    now=time.time()
    pair=str(asset.get("pair") or "")
    if _is_otc_asset(asset):
        return analyze_otc_asset(
            asset,candles,price,
            forced_strategy=forced_strategy,
            learning_campaign=learning_campaign,
            require_high_volume=require_high_volume,
        )
    cs=_closed_1m(candles,now)
    if len(cs)<MIN_CLOSED_CANDLES:
        _diag(pair,"history_short",closed=len(cs),required=MIN_CLOSED_CANDLES)
        return None

    blocks=_complete_15m_blocks(cs,now)
    if not blocks:
        _diag(pair,"no_complete_15m_block",closed=len(cs),unique_minutes=len({int(x["time"]) for x in cs}))
        return None

    last=cs[-1]
    previous=cs[-2]
    anchor_ts=int(blocks[-1]["time"])
    avwap,avwap_volume=_anchored_vwap(cs,anchor_ts)
    if avwap<=0:
        _diag(pair,"invalid_avwap",avwap=avwap)
        return None

    profile=_volume_profile(cs)
    if not profile or float(profile.get("poc") or 0.0)<=0:
        _diag(pair,"invalid_profile",profile=bool(profile))
        return None

    px=float(last["close"])
    poc=float(profile["poc"])
    vah=float(profile["vah"])
    val=float(profile["val"])
    slope=avwap-float(_anchored_vwap(cs[:-1],anchor_ts)[0])
    slope_features=_avwap_slope_features(cs,anchor_ts)
    migration=_profile_migration(cs)

    up=px>avwap and px>poc
    down=px<avwap and px<poc
    if not (up or down):
        _diag(pair,"no_two_indicator_alignment",price=round(px,10),avwap=round(avwap,10),poc=round(poc,10),vah=round(vah,10),val=round(val,10))
        return None

    direction="UP" if up else "DOWN"
    # Bollinger Bands 18/2 are a secondary M1 confirmation layer only.
    # No BB state can change the AVWAP+VP direction or block the scheduler.
    bb=_bollinger_confirmation(cs,direction,period=18,multiplier=2.0)
    slope_aligned_steps=(
        sum(
            1 for s in (
                slope_features["avwap_slope_1"],
                slope_features["avwap_slope_2"],
                slope_features["avwap_slope_3"],
            ) if s>0
        ) if direction=="UP" else
        sum(
            1 for s in (
                slope_features["avwap_slope_1"],
                slope_features["avwap_slope_2"],
                slope_features["avwap_slope_3"],
            ) if s<0
        )
    )
    slope_persistent=slope_aligned_steps>=2

    value_acceptance=(px>=vah) if direction=="UP" else (px<=val)
    prev_key=max(avwap,poc) if direction=="UP" else min(avwap,poc)
    current_key=max(avwap,poc) if direction=="UP" else min(avwap,poc)
    level_reclaim=(
        float(previous["close"])<=prev_key and px>current_key
        if direction=="UP"
        else float(previous["close"])>=prev_key and px<current_key
    )

    migration_norm=float((migration or {}).get("poc_migration_norm") or 0.0)
    migration_aligned=(
        migration_norm>0.05 if direction=="UP"
        else migration_norm<-0.05
    )
    migration_against=(
        migration_norm<-0.15 if direction=="UP"
        else migration_norm>0.15
    )

    value_width=max(vah-val,1e-12)
    profile_range=max(float(profile["range_high"])-float(profile["range_low"]),1e-12)
    value_position=(
        "ABOVE_VALUE" if px>vah else
        "BELOW_VALUE" if px<val else
        "UPPER_VALUE" if px>poc else
        "LOWER_VALUE" if px<poc else "AT_POC"
    )

    # Alligator confirmation is mandatory for the live candidate.
    # It validates the AVWAP+VP direction; it never creates or flips direction.
    alligator=_alligator_confirmation(cs,direction)
    if not bool(alligator.get("ready")):
        _diag(pair,"alligator_not_ready",details=alligator.get("reason"))
        return None
    if not bool(alligator.get("confirmed")):
        _diag(
            pair,"alligator_confirmation_rejected",
            direction=direction,
            aligned=alligator.get("aligned"),
            sloping=alligator.get("sloping"),
            price_position=alligator.get("price_position"),
        )
        return None

    # LIVE EXACT-SETUP FILTER:
    # Only the exact point identified by the current result analysis enters the
    # live selector: ABOVE_VALUE + no level reclaim + persistent AVWAP slope.
    # This is an empirical qualification rule, not a promise of future wins.
    exact_live_setup=(
        (
            (direction=="UP" and value_position=="ABOVE_VALUE")
            or (direction=="DOWN" and value_position=="BELOW_VALUE")
        )
        and level_reclaim is False
        and slope_persistent is True
    )
    if not exact_live_setup:
        _diag(
            pair,"exact_live_setup_rejected",
            direction=direction,value_position=value_position,
            level_reclaim=level_reclaim,slope_persistent=slope_persistent
        )
        return None

    coverage=float(profile.get("volume_coverage") or 0.0)
    real_coverage=float(profile.get("real_volume_coverage") or 0.0)
    tick_coverage=float(profile.get("tick_volume_coverage") or 0.0)
    tick_activity_coverage=float(profile.get("tick_activity_coverage") or 0.0)
    tick_activity_partial_bars=int(profile.get("tick_activity_partial_bars") or 0)
    # Keep quality semantics truthful. "HIGH" is reserved for broker-reported
    # real/traded volume. Broker tick volume and locally observed tick activity
    # are useful proxies but are never labelled as real volume.
    if real_coverage>=0.80:
        volume_quality="HIGH"
    elif tick_coverage>=0.80:
        volume_quality="TICK_VOLUME"
    elif tick_activity_coverage>=0.80:
        volume_quality="TICK_ACTIVITY"
    else:
        volume_quality="LOW"
    volume_bars=int(profile.get("volume_bars") or 0)
    volume_proxy_mode=real_coverage<HIGH_VOLUME_MIN_COVERAGE
    high_volume_confirmed=bool(
        real_coverage>=HIGH_VOLUME_MIN_COVERAGE
        and volume_bars>=int(PROFILE_LOOKBACK*HIGH_VOLUME_MIN_COVERAGE)
    )
    # The offline/unit-test contract stays strict by default: real broker volume
    # must satisfy the HIGH-volume definition. The live scheduler can temporarily
    # inspect the same AVWAP+VP setup without this discovery gate so it can first
    # pin Event-1 and prove genuinely HIGH observed tick activity. That proxy is
    # explicitly named HIGH_TICK_ACTIVITY_PROXY downstream and never relabelled
    # as traded volume.
    if require_high_volume and not high_volume_confirmed:
        _diag(
            pair,"high_volume_required",
            real_volume_coverage=round(real_coverage,3),
            volume_bars=int(profile.get("volume_bars") or 0),
            required_bars=int(PROFILE_LOOKBACK*HIGH_VOLUME_MIN_COVERAGE),
            volume_mode=profile.get("volume_mode"),
        )
        return None

    if volume_proxy_mode:
        _diag(
            pair,"volume_proxy_candidate",
            coverage=round(coverage,3),
            volume_bars=int(profile.get("volume_bars") or 0),
            volume_mode=profile.get("volume_mode"),
        )

    # One-minute continuation guard: the exact setup must still have upward
    # closed-M1 continuation at the decision candle. This is a zero-network
    # price-action check on the same closed candles already used by the Brain.
    last_open=float(last["open"])
    last_close=float(last["close"])
    previous_close=float(previous["close"])
    m1_continuation_ok=(
        (
            (direction=="UP" and last_close>=last_open and last_close>previous_close)
            or (direction=="DOWN" and last_close<=last_open and last_close<previous_close)
        )
    )
    if not m1_continuation_ok:
        _diag(
            pair,"m1_continuation_failed",
            direction=direction,
            last_open=round(last_open,10),
            last_close=round(last_close,10),
            previous_close=round(previous_close,10),
        )
        return None

    # Stronger anti-chop confirmation for the 1m/2m production lane:
    # require directional consistency across the recent closed-M1 sequence
    # and a close near the candle extreme. This does not create or flip
    # direction; it only rejects weak continuation candles.
    recent3=cs[-3:]
    aligned3=0
    try:
        for rc in recent3:
            ro=float(rc["open"]); rh=float(rc["high"]); rl=float(rc["low"]); rcx=float(rc["close"])
            aligned3 += 1 if (
                (direction=="UP" and rcx>=ro and rcx>float(recent3[0]["close"]))
                or
                (direction=="DOWN" and rcx<=ro and rcx<float(recent3[0]["close"]))
            ) else 0
    except (TypeError,ValueError,KeyError):
        aligned3=0
    last_range=max(float(last["high"])-float(last["low"]),1e-12)
    last_close_position=(last_close-float(last["low"]))/last_range
    last_body_ratio=abs(last_close-last_open)/last_range
    recent_directional_confirmation=(
        aligned3>=2
        and (
            (direction=="UP" and last_close_position>=0.60)
            or
            (direction=="DOWN" and last_close_position<=0.40)
        )
        and last_body_ratio>=0.35
    )
    if not recent_directional_confirmation:
        _diag(
            pair,"m1_strong_continuation_rejected",
            direction=direction,
            aligned3=aligned3,
            last_close_position=round(last_close_position,3),
            last_body_ratio=round(last_body_ratio,3),
        )
        return None

    # A one-minute expiry benefits from directional acceptance or a genuine
    # reclaim of AVWAP/POC. A mere location above/below both levels while still
    # trapped inside the value area is treated as a weak setup.
    directional_acceptance=bool(value_acceptance or level_reclaim)
    if not directional_acceptance:
        _diag(
            pair,"inside_value_without_acceptance",
            direction=direction,price=round(px,10),avwap=round(avwap,10),
            poc=round(poc,10),vah=round(vah,10),val=round(val,10),
            reclaim=level_reclaim
        )
        return None

    if migration_against:
        _diag(pair,"poc_migration_against",direction=direction,migration_norm=round(migration_norm,4))
        return None

    # Alligator is already a mandatory gate; add a small confluence
    # bonus because it is fully aligned with the authoritative direction.
    alligator_bonus=3

    # Bollinger 18/2 confirmation affects confluence/ranking only.
    # It is deliberately soft so an isolated BB disagreement cannot suppress
    # otherwise valid AVWAP+VP setups or disturb the 3-minute signal cadence.
    bb_bonus=2 if bb.get("bb_confirmation")=="ALIGNED" else 0

    # If a previous profile exists and the POC is migrating in the same
    # direction, that is a reinforcing confluence. Flat migration is neutral.
    score=90
    if slope_persistent:
        score+=3
    if value_acceptance:
        score+=3
    elif level_reclaim:
        score+=1
    if migration_aligned:
        score+=2
    if alligator_bonus:
        score+=alligator_bonus
    if bb_bonus:
        score+=bb_bonus
    if high_volume_confirmed:
        score+=2

    confidence=min(99,max(0,int(score)))

    trend="AVWAP_BULLISH" if up else "AVWAP_BEARISH"
    structure="ABOVE_AVWAP_POC" if up else "BELOW_AVWAP_POC"

    features={
        "anchored_vwap":avwap,
        "volume_profile_poc":poc,
        "volume_profile_vah":vah,
        "volume_profile_val":val,
        "avwap_slope":slope,
        "avwap_slope_1":slope_features["avwap_slope_1"],
        "avwap_slope_2":slope_features["avwap_slope_2"],
        "avwap_slope_3":slope_features["avwap_slope_3"],
        "avwap_slope_persistence":slope_features["slope_persistence"],
        "profile_poc_delta":float((migration or {}).get("poc_delta") or 0.0),
        "profile_poc_migration_norm":migration_norm,
        "profile_previous_poc":(migration or {}).get("previous_poc"),
        "profile_migration_available":bool((migration or {}).get("available")),
        "alligator_confirmed":True,
        "alligator_confirmation":"CONFIRMED",
        "alligator_periods":alligator.get("periods","13/8,8/5,5/3"),
        "alligator_jaw":alligator.get("jaw"),
        "alligator_teeth":alligator.get("teeth"),
        "alligator_lips":alligator.get("lips"),
        "alligator_prev_jaw":alligator.get("prev_jaw"),
        "alligator_prev_teeth":alligator.get("prev_teeth"),
        "alligator_prev_lips":alligator.get("prev_lips"),
        "alligator_aligned":True,
        "alligator_sloping":True,
        "alligator_price_position":True,
        "alligator_timing_ok":True,
        "alligator_spread":alligator.get("spread"),
        "alligator_prev_spread":alligator.get("prev_spread"),
        "alligator_spread_ratio":alligator.get("spread_ratio"),
        "alligator_latest_closed_candle_ts":alligator.get("latest_closed_candle_ts"),
        "alligator_closed_age_seconds":alligator.get("closed_age_seconds"),
        "alligator_timing_max_age_seconds":alligator.get("timing_max_age_seconds"),
        "alligator_min_spread_ratio":alligator.get("min_spread_ratio"),
        "alligator_breakout":bool(alligator.get("breakout")),
        "alligator_breakout_confirmed":bool(alligator.get("breakout_confirmed")),
        "alligator_breakout_direction":alligator.get("breakout_direction"),
        "alligator_breakout_candle_ts":alligator.get("breakout_candle_ts"),
        "alligator_breakout_previous_close":alligator.get("breakout_previous_close"),
        "alligator_breakout_current_close":alligator.get("breakout_current_close"),
        "alligator_bonus":alligator_bonus,
        "bb_period":bb.get("bb_period",18),
        "bb_multiplier":bb.get("bb_multiplier",2.0),
        "bb_ready":bb.get("bb_ready",False),
        "bb_confirmation":bb.get("bb_confirmation","UNAVAILABLE"),
        "bb_basis":bb.get("bb_basis"),
        "bb_upper":bb.get("bb_upper"),
        "bb_lower":bb.get("bb_lower"),
        "bb_bandwidth":bb.get("bb_bandwidth"),
        "bb_bandwidth_expanding":bb.get("bb_bandwidth_expanding",False),
        "bb_confirmation_bonus":bb_bonus,
        "profile_range_high":profile["range_high"],
        "profile_range_low":profile["range_low"],
        "profile_range":profile_range,
        "profile_value_area_width":value_width,
        "profile_total_volume":profile["total_volume"],
        "profile_bins":profile["bins"],
        "volume_coverage":coverage,
        "volume_bars":int(profile.get("volume_bars") or 0),
        "high_volume_confirmed":high_volume_confirmed,
        "high_volume_gate_pending":bool((not high_volume_confirmed) and (not require_high_volume)),
        "high_volume_min_coverage":HIGH_VOLUME_MIN_COVERAGE,
        "high_volume_required_bars":int(PROFILE_LOOKBACK*HIGH_VOLUME_MIN_COVERAGE),
        "volume_mode":profile.get("volume_mode"),
        "volume_quality":volume_quality,
        "volume_data_class":(
            "REAL_VOLUME" if real_coverage>=0.80
            else "TICK_VOLUME" if tick_coverage>=0.80
            else "TICK_ACTIVITY_PROXY" if tick_activity_coverage>0.0
            else "NO_BROKER_VOLUME"
        ),
        "real_volume_verified":bool(real_coverage>=0.80),
        "real_volume_bars":int(profile.get("real_volume_bars") or 0),
        "real_volume_coverage":float(profile.get("real_volume_coverage") or 0.0),
        "tick_volume_bars":int(profile.get("tick_volume_bars") or 0),
        "tick_volume_coverage":float(profile.get("tick_volume_coverage") or 0.0),
        "tick_activity_bars":int(profile.get("tick_activity_bars") or 0),
        "tick_activity_coverage":float(profile.get("tick_activity_coverage") or 0.0),
        "tick_activity_partial_bars":tick_activity_partial_bars,
        "volume_proxy_mode":volume_proxy_mode,
        "volume_gate_mode":(
            "REAL_VOLUME_REQUIRED" if require_high_volume else
            "LIVE_DISCOVERY_PENDING_HIGH_TICK_ACTIVITY"
        ),
        "m1_continuation_ok":m1_continuation_ok,
        "m1_recent_aligned_candles":int(aligned3),
        "m1_last_close_position":round(last_close_position,4),
        "m1_last_body_ratio":round(last_body_ratio,4),
        "m1_strong_continuation_confirmed":bool(recent_directional_confirmation),
        "value_position":value_position,
        "value_area_acceptance":value_acceptance,
        "level_reclaim":level_reclaim,
        "slope_persistent":slope_persistent,
        "exact_live_setup":exact_live_setup,
        "poc_migration_aligned":migration_aligned,
        "poc_migration_against":migration_against,
        "anchor_15m_start_ts":anchor_ts,
        "avwap_volume":avwap_volume,
        "m1_sequence_signature":_m1_sequence_signature(cs,6),
        "market_regime":_market_regime(
            direction,slope_persistent,value_acceptance,level_reclaim,
            migration_aligned,migration_against,value_position
        ),
        "decision_time_bucket":_decision_time_bucket(last["time"]),
    }

    result={
        "pair":str(asset.get("pair") or ""),
        "display_name":str(
            asset.get("display_name")
            or asset.get("title")
            or asset.get("name")
            or asset.get("pair")
            or ""
        ),
        "direction":direction,
        "confidence":confidence,
        "strategy":ALLOWED_STRATEGY,
        "expiry_minutes":1,
        "pattern":"AVWAP_VOLUME_PROFILE_ALIGNMENT",
        "trend_15m":trend,
        "structure_1m":structure,
        "market_quality":float(score),
        "confluence_score":float(score),
        "direction_agreement":1.0,
        "value_area_acceptance":value_acceptance,
        "reason":(
            f"Closed M1 price={px:.8f}; AVWAP={avwap:.8f}; POC={poc:.8f}; "
            f"VAH={vah:.8f}; VAL={val:.8f}; AVWAP_slope={slope:.8f}; "
            f"slope_persistence={slope_aligned_steps}/3; value={value_position}; "
            f"reclaim={level_reclaim}; POC_migration={migration_norm:.4f}; "
            f"volume_quality={volume_quality}; HIGH_VOLUME=CONFIRMED; AVWAP+POC aligned; "
            f"Alligator(13/8,8/5,5/3)=CONFIRMED; "
            f"M1_strong_continuation={aligned3}/3 body={last_body_ratio:.2f} close_pos={last_close_position:.2f}; "
            f"BB(18,2)={bb.get('bb_confirmation','UNAVAILABLE')}."
        ),
        "indicator_features":features,
        "indicators":features,
        "avwap":avwap,
        "poc":poc,
        "vah":vah,
        "val":val,
        "avwap_slope":slope,
        "entry_candle_ts":last["time"],
        "closed_1m_ts":last["time"],
        "closed_15m_ts":anchor_ts,
        "decision_candle_closed":True,
        "price":px,
        "five_minute_eligible":False,
        "self_strategy_version":"AVWAP_VP_V2",
        "strategy_candidates":[{
            "strategy":ALLOWED_STRATEGY,
            "direction":direction,
            "score":confidence,
            "expiry_minutes":1,
            "self_strategy_version":"AVWAP_VP_V2",
        }],
        "strategy_audit":[{
            "strategy":ALLOWED_STRATEGY,
            "active_for_live":True,
            "up_qualified":bool(up),
            "down_qualified":bool(down),
        }],
        "strategy_audit_count":1,
        "indicator_audit_scope":"AVWAP_VOLUME_PROFILE_WITH_ALLIGATOR_13_8_8_5_5_3_TIMED_CLOSED_CANDLE_AND_BB18_2_CONFIRMATION",
        "m1_sequence_signature":features["m1_sequence_signature"],
        "market_regime":features["market_regime"],
        "decision_time_bucket":features["decision_time_bucket"],
    }
    return result